import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

interface InvoiceData {
  invoiceNumber: string;
  invoiceDate: Date;
  vendorName: string;
  gstNumber: string;
  rfqTitle: string;
  quantity: number;
  poNumber: string;
  subtotal: number;
  tax: number;
  total: number;
}

export async function generateInvoicePdf(data: InvoiceData): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]); // A4 size
  const { height } = page.getSize();

  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const darkBlue = rgb(0.1, 0.15, 0.35);
  const mediumBlue = rgb(0.2, 0.3, 0.6);
  const black = rgb(0, 0, 0);
  const gray = rgb(0.4, 0.4, 0.4);
  const lightGray = rgb(0.85, 0.85, 0.85);

  let y = height - 50;

  // ─── Header ───
  page.drawRectangle({
    x: 0,
    y: y - 10,
    width: 595,
    height: 60,
    color: darkBlue,
  });

  page.drawText('VendorBridge', {
    x: 50,
    y: y + 10,
    size: 24,
    font: fontBold,
    color: rgb(1, 1, 1),
  });

  page.drawText('INVOICE', {
    x: 430,
    y: y + 10,
    size: 20,
    font: fontBold,
    color: rgb(1, 1, 1),
  });

  y -= 80;

  // ─── Invoice Details ───
  const drawLabelValue = (label: string, value: string, x: number, yPos: number) => {
    page.drawText(label, { x, y: yPos, size: 10, font: fontBold, color: gray });
    page.drawText(value, { x, y: yPos - 15, size: 11, font: fontRegular, color: black });
  };

  drawLabelValue('Invoice Number', data.invoiceNumber, 50, y);
  drawLabelValue('Invoice Date', data.invoiceDate.toLocaleDateString('en-IN', {
    year: 'numeric', month: 'long', day: 'numeric',
  }), 300, y);

  y -= 50;

  drawLabelValue('PO Number', data.poNumber, 50, y);
  drawLabelValue('RFQ Title', data.rfqTitle, 300, y);

  y -= 60;

  // ─── Vendor Details Section ───
  page.drawText('VENDOR DETAILS', {
    x: 50,
    y,
    size: 12,
    font: fontBold,
    color: mediumBlue,
  });

  y -= 5;
  page.drawRectangle({ x: 50, y, width: 495, height: 1, color: mediumBlue });

  y -= 20;
  drawLabelValue('Vendor Name', data.vendorName, 50, y);
  drawLabelValue('GST Number', data.gstNumber, 300, y);

  y -= 60;

  // ─── Items Table ───
  page.drawText('ITEMS', {
    x: 50,
    y,
    size: 12,
    font: fontBold,
    color: mediumBlue,
  });

  y -= 5;
  page.drawRectangle({ x: 50, y, width: 495, height: 1, color: mediumBlue });

  y -= 25;

  // Table header
  page.drawRectangle({ x: 50, y: y - 5, width: 495, height: 25, color: lightGray });

  page.drawText('Description', { x: 60, y, size: 10, font: fontBold, color: black });
  page.drawText('Quantity', { x: 280, y, size: 10, font: fontBold, color: black });
  page.drawText('Unit Price', { x: 360, y, size: 10, font: fontBold, color: black });
  page.drawText('Amount', { x: 470, y, size: 10, font: fontBold, color: black });

  y -= 30;

  // Table row
  const unitPrice = data.quantity > 0 ? data.subtotal / data.quantity : data.subtotal;
  page.drawText(data.rfqTitle, { x: 60, y, size: 10, font: fontRegular, color: black });
  page.drawText(String(data.quantity), { x: 290, y, size: 10, font: fontRegular, color: black });
  page.drawText(`Rs. ${unitPrice.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, {
    x: 355, y, size: 10, font: fontRegular, color: black,
  });
  page.drawText(`Rs. ${data.subtotal.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, {
    x: 460, y, size: 10, font: fontRegular, color: black,
  });

  y -= 15;
  page.drawRectangle({ x: 50, y, width: 495, height: 1, color: lightGray });

  y -= 40;

  // ─── Totals ───
  const totalsX = 360;

  page.drawText('Subtotal:', { x: totalsX, y, size: 11, font: fontRegular, color: gray });
  page.drawText(`Rs. ${data.subtotal.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, {
    x: 460, y, size: 11, font: fontRegular, color: black,
  });

  y -= 22;

  page.drawText('GST (18%):', { x: totalsX, y, size: 11, font: fontRegular, color: gray });
  page.drawText(`Rs. ${data.tax.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, {
    x: 460, y, size: 11, font: fontRegular, color: black,
  });

  y -= 5;
  page.drawRectangle({ x: totalsX, y, width: 185, height: 1, color: black });

  y -= 20;

  page.drawText('TOTAL:', { x: totalsX, y, size: 13, font: fontBold, color: darkBlue });
  page.drawText(`Rs. ${data.total.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`, {
    x: 460, y, size: 13, font: fontBold, color: darkBlue,
  });

  // ─── Footer ───
  page.drawRectangle({
    x: 0,
    y: 0,
    width: 595,
    height: 40,
    color: darkBlue,
  });

  page.drawText('Generated by VendorBridge ERP', {
    x: 200,
    y: 15,
    size: 9,
    font: fontRegular,
    color: rgb(0.7, 0.7, 0.8),
  });

  return pdfDoc.save();
}
